# Execução conservadora para ambientes locais com memória limitada.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.vfs.watch=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.enabled=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true


