const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '../..');
const cockpit = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/screens/autocal-cockpit.js'), 'utf8');
const arCss = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/styles-autocal-refino.css'), 'utf8');
const cockpitCss = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/styles-autocal-cockpit.css'), 'utf8');
const chart = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/components/curve-chart.js'), 'utf8');
const api = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/core/autocal-api.js'), 'utf8');
const provider = fs.readFileSync(path.join(root, 'app/src/main/java/com/omegas/prohub/autocal/AutoCalBridgeProvider.kt'), 'utf8');
const manager = fs.readFileSync(path.join(root, 'app/src/main/java/com/omegas/prohub/autocal/AutoCalNativeActionManager.kt'), 'utf8');

assert.equal(cockpit.includes('ar-chart-card'), true);
// Revisto (W2): asserções sobre blocos podados do AutoCal (cabeçalho, Detalhes, Histórico, popover de opções) foram removidas.
// Revisto (W2): o cabeçalho ar-status saiu do AutoCal (o gráfico ocupa a área toda).
assert.equal(cockpit.includes('class="ar-status"'), false);
assert.equal(cockpit.includes('data-autocal-read'), false);
assert.equal(cockpit.includes('data-autocal-chart-action="zoom-in"'), false);
assert.equal(cockpit.includes('data-autocal-chart-action="zoom-out"'), false);
assert.equal(cockpit.includes('data-autocal-chart-action="fit"'), false);
assert.equal(cockpit.includes('chartTransform()'), false);
assert.equal(cockpit.includes('bindChartGestures('), false);
assert.equal(cockpit.includes('Injeção (ms)'), true);
// Revisto (W2): o chip de combustível (autocalLiveFuel) saiu do AutoCal junto com o cabeçalho.
assert.equal(cockpit.includes("fuelChip.dataset.fuelState = fuelState.kind"), true);
assert.equal(cockpitCss.includes('.autocal-fuel-chip[data-fuel-state="gas"]'), true);
assert.equal(chart.includes('MAP (bar)'), true);
assert.equal(cockpit.includes('ns.CurveChart.buildSvg(model'), true);
assert.equal(cockpit.includes('const readerReady ='), false);
assert.equal(cockpit.includes('this.api.readerSnapshot()'), false);
assert.equal(cockpit.includes('this.api.acquisitionSnapshot()'), false);
assert.equal(cockpit.includes('AUTOCAL_PROJECTION_UNAVAILABLE'), true);
assert.equal(cockpitCss.includes('touch-action: pan-y'), true);
assert.equal(cockpit.includes('autocal-now-card'), false);
assert.equal(cockpit.includes('autocal-read-card'), false);
assert.equal(arCss.includes('.ar-chart-card'), true);
assert.equal(cockpitCss.includes('.autocal-secondary-stack'), true);
assert.equal(cockpit.indexOf('autocal-chart-workspace') < cockpit.indexOf('autocalReferenceChart'), true);
assert.equal(cockpit.indexOf('autocalReferenceChart') < cockpit.indexOf('autocalChartInspector'), true);
assert.equal(cockpit.includes("addHook('status'"), true);
assert.equal(cockpit.includes("addHook('context'"), false);
assert.equal(cockpit.includes('setInterval'), false);
assert.equal(cockpit.includes('NUM_BUF_UPD_GAS'), true);
// Revisto (P3): a lista de eventos de correlação (renderEvents) não tinha onde aparecer e saiu.
assert.equal(cockpit.includes('renderEvents'), false);
assert.equal(cockpit.includes("data-autocal-toggle"), true);
assert.equal(cockpit.includes("data-autocal-action=\"ENABLE_AUTO_CAL\""), false);
assert.equal(cockpit.includes("data-autocal-action=\"DISABLE_AUTO_CAL\""), false);
assert.equal(cockpit.includes("data-autocal-action=\"RESET_PETROL\""), true);
assert.equal(cockpit.includes("data-autocal-action=\"RESET_GAS\""), true);
// Revisto (P2): zerar a Curva K só existe na própria aba Curva K; o AutoCal não repete o botão.
assert.equal(cockpit.includes("data-autocal-action=\"RESET_K_FACTOR\""), false);
assert.equal(cockpit.includes("Resetar Curva K para 1,000"), false);
assert.equal(cockpit.includes("data-autocal-action=\"NEUTRALIZE_LIVE_K\""), false);
assert.equal(cockpit.includes("data-autocal-action=\"RESET_ALL\""), false);
assert.equal(cockpit.includes("data-autocal-action=\"MANUAL_AUTOMATCH\""), false);
assert.equal(cockpit.includes("data-autocal-action=\"FINISH_AUTOCAL\""), false,
  'Finish AutoCal original é compatibilidade técnica e não pode virar CTA normal');
assert.equal(cockpit.includes("class=\"autocal-finish-action\""), false);
assert.equal(cockpit.includes("data-autocal-action=\"FINISH_AUTOMATCH\""), false);
assert.equal(cockpitCss.includes('.autocal-finish-action'), false);
// Revisto (W2): sem textos fixos, sem "Mais opções" e sem popover: barra única Pausar / Reler GNV / Reler gasolina.
assert.equal(cockpit.includes('Os ajustes automáticos são decididos pela ECU.'), false);
assert.equal(cockpit.includes('Mais opções'), false);
assert.equal(cockpit.includes('>Reler GNV<'), true);
assert.equal(cockpit.includes('>Reler gasolina<'), true);
assert.equal(cockpit.includes('Nada aqui roda automaticamente.'), false);
assert.equal(cockpit.includes('autoMatchQuotaReached'), true);
assert.equal(cockpit.includes('AutoMatch automático '), true);
assert.equal(cockpit.includes('· limite atingido'), true);
assert.equal(cockpit.includes('<summary>Corrigir aquisição</summary>'), false);
assert.equal(cockpit.includes('autocal-reacquire-action'), true);
assert.equal(cockpit.indexOf('data-autocal-toggle') < cockpit.indexOf('data-autocal-action="RESET_GAS"'), true);
assert.equal(cockpitCss.includes('.autocal-reacquire-action'), true);
assert.equal(cockpitCss.includes('.autocal-reset-advanced'), false);
assert.equal(cockpit.includes('MANUAL_AUTOMATCH'), false);
assert.equal(cockpit.includes('NATIVE_AUTOMATCH'), false);
assert.equal(cockpit.includes('runOperational(action)'), true);
assert.equal(cockpit.includes('setAcquisitionEnabled'), true);
assert.equal(cockpit.includes('prepare('), true);
assert.equal(cockpit.includes('execute(prepared.preparationId)'), true);
assert.equal(cockpit.includes('Continuar para confirmação Android'), false);
assert.equal(cockpit.includes('Confirmação Android aberta'), false);
// Revisto (P3): o cartão "Executar agora" (renderReview) era código morto: um toque, conferência na ECU.
assert.equal(cockpit.includes('Executar agora'), false);
assert.equal(cockpit.includes('Conferindo na ECU'), true);
assert.equal(cockpit.includes('VERIFYING_FINISH'), true);
assert.equal(cockpit.includes('RESETTING_K'), true);
assert.equal(cockpit.includes("querySelectorAll('[data-autocal-action]')"), true);
assert.equal(cockpit.includes('FACTOR_CHANGE_CONFIRMED'), true);
assert.equal(cockpit.includes('NO_FACTOR_CHANGE_OBSERVED'), true);
assert.equal(cockpit.includes('sem par antes/depois'), true);
assert.equal(cockpit.includes('recovery?.nextAction'), true);
// Revisto (P2 clareza): "Próximo:" virou "Próximo passo:".
assert.equal(cockpit.includes('Próximo passo: '), true);
assert.equal(cockpit.includes('dataset.reasonCode'), true);
assert.equal(cockpit.includes('K mudou '), true);
assert.equal(cockpitCss.includes('.autocal-automatch-evidence[data-state="FACTOR_CHANGE_CONFIRMED"]'), true);
assert.equal(cockpit.includes('Consultar ECU'), false);
assert.equal(cockpit.includes('autocal-secondary-rail'), false);
assert.equal(arCss.includes('.ar-secondary'), true);
assert.equal(api.includes('prepareNativeAction'), true);
assert.equal(api.includes('executeNativeAction'), true);
assert.equal(api.includes('preparePointDelete'), true);
assert.equal(api.includes('preparePointDeleteBatch'), true);
assert.equal(cockpit.includes('selectedAcquiredPoints = new Set()'), true);
assert.equal(cockpit.includes('this.selectedAcquiredPoints.clear();'), true);
// Revisto (P2 seleção): tocar no ponto marca/desmarca; a barra tem só "Reaprender N pontos" e "Cancelar".
assert.equal(cockpit.includes('data-autocal-toggle-point-selection'), false);
assert.equal(cockpit.includes('tapAcquiredPoint('), true);
assert.equal(cockpit.includes('data-autocal-clear-point-selection>Cancelar<'), true);
assert.equal(cockpit.includes('data-autocal-reacquire-selected'), true);
assert.equal(cockpit.includes('requestSelectedPointReacquisition()'), true);
assert.equal(cockpitCss.includes('.autocal-acquired-hit.batch-selected'), true);
assert.equal(cockpit.includes('data-autocal-acquired-index'), true);
assert.equal(cockpit.includes('data-autocal-reacquire-point'), false);
assert.equal(cockpit.includes("PETR_INJ_TBUF_GAS"), true);
assert.equal(cockpit.includes("MNFLD_PRESS_BUF_GAS"), true);
assert.equal(cockpit.includes("PETR_INJ_TBUF"), true);
assert.equal(cockpit.includes("MNFLD_PRESS_BUF"), true);
assert.equal(cockpit.includes("'Reaprender '"), true);
assert.equal(cockpit.includes("acquisitionState: acquired ? 'ACQUIRED' : 'COLLECTING'"), true);
assert.equal(chart.includes("data-acquisition-state"), true);
assert.equal(cockpit.includes("ainda aprendendo"), true);
assert.equal(cockpitCss.includes('.autocal-acquired-point.collecting'), true);
assert.equal(cockpitCss.includes('.autocal-acquired-point.acquired'), true);
assert.equal(manager.includes('manualAutoMatchExposed'), false);
assert.equal(manager.includes('NATIVE_AUTOMATCH'), false);
assert.equal(provider.includes('hub/autocal-ui.js'), false);
assert.equal(provider.includes('postDelayed'), false);
assert.equal(provider.includes('addJavascriptInterface'), true);
console.log('AUTOCAL_COCKPIT_CONTRACT=PASS');
