'use strict';
// Revisto (W2): AutoCal sem cabeçalho/Detalhes/Histórico/Opções; asserções sobre esses blocos foram removidas (1).
// Revisto (W2): AutoCal sem cabeçalho/Detalhes/Histórico/Opções; asserções sobre esses blocos foram removidas (1).

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '../..');
const cockpit = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/screens/autocal-cockpit.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'app/src/main/assets/ui/styles-autocal-cockpit.css'), 'utf8');

assert.ok(cockpit.includes('autocalResetComparison'),
  'cockpit must reserve a native before/after comparison after acquisition or curve reset');
assert.ok(cockpit.includes('referenceComparison(this.previousReferencePoints'),
  'before/after comparison must be generated by the AutoCal UX model, not handwritten copy');
assert.ok(cockpit.includes('liveLabelAnchor(projected'),
  'AGORA label must use a bounded anchor to avoid overlapping the curve at the top/right edge');
assert.ok(cockpit.includes('liveFuelState('),
  'AutoCal must normalize MP48 fuel/state explicitly instead of guessing fuel in render code');
// Actual graph size and visible point context are verified by the rendered layout gate.
const arCss = require('fs').readFileSync(require('path').join(__dirname, '../../app/src/main/assets/ui/styles-autocal-refino.css'), 'utf8');
for (const selector of ['html body .ar-shell .ar-legend', 'html body .ar-shell .ar-readout']) {
  const blocks = [...arCss.matchAll(/([^{}]+)\{([^{}]*)\}/g)]
    .filter(match => match[1].split(',').map(item => item.trim()).includes(selector))
    .map(match => match[2]);
  assert.ok(blocks.length, selector + ' CSS block missing');
  assert.ok(blocks.some(block => /position:\s*static/.test(block)),
    selector + ' must declare a static operational layout outside the graph');
  assert.ok(!blocks.some(block => /position:\s*absolute/.test(block)),
    selector + ' must not sit over the AutoCal graph in multimedia use');
}

const context = { console, setTimeout: () => 0, clearTimeout: () => {} };
context.globalThis = context;
vm.createContext(context);
require('./_support.cjs').preload(context);
vm.runInContext(cockpit, context, { filename: 'autocal-cockpit.js' });

const model = context.OmegasUi.AutoCalUxModel;
const comparison = model.referenceComparison(
  [
    { index: 0, petrolMs: 1.0, petrolMapBar: 0.40, gasMapBar: 0.44 },
    { index: 1, petrolMs: 2.0, petrolMapBar: 0.60, gasMapBar: 0.66 },
  ],
  [
    { index: 0, petrolMs: 1.0, petrolMapBar: 0.41, gasMapBar: 0.47 },
    { index: 1, petrolMs: 2.0, petrolMapBar: 0.62, gasMapBar: 0.69 },
  ],
);
assert.equal(comparison.available, true);
assert.equal(comparison.count, 2);
assert.equal(comparison.mapDeltaAvgBar, 0.015);
assert.equal(comparison.gasDeltaAvgBar, 0.03);

const anchor = model.liveLabelAnchor({ x: 960, y: 24 }, {
  xFor: value => value === 1 ? 972 : 64,
  yFor: value => value === 1 ? 22 : 352,
  xMin: 0,
  xMax: 1,
  yMin: 0,
  yMax: 1,
});
assert.equal(anchor.textAnchor, 'end');
assert.ok(anchor.y >= 48, 'top-edge AGORA label must move below the point');

assert.equal(JSON.stringify(model.liveFuelState('GNV_ATIVO')), JSON.stringify({ kind: 'gas', label: 'GNV', active: true }));
assert.equal(JSON.stringify(model.liveFuelState('GASOLINA_ATIVA')), JSON.stringify({ kind: 'petrol', label: 'Gasolina', active: true }));
assert.equal(JSON.stringify(model.liveFuelState('TRANSICAO_COM_PULSO_GNV')), JSON.stringify({ kind: 'transition', label: 'Transição', active: false }));

console.log('AUTOCAL_MULTIMEDIA_SOPHISTICATION=PASS');
