'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '../..');
const xml = fs.readFileSync(path.join(root, 'app/build/test-results/testDebugUnitTest/TEST-com.omegas.prohub.LearningLatencyContractTest.xml'), 'utf8');
const match = xml.match(/UI_PAYLOAD=(.+)$/m);
assert.ok(match, 'Run LearningLatencyContractTest before this cross-runtime contract');
const payload = JSON.parse(match[1]);
assert.deepEqual(payload.assistedCalibration, payload.assisted_calibration);
assert.equal(payload.assistedCalibration.automatic, false);
assert.equal(payload.assistedCalibration.humanConfirmationRequired, true);
const context = { console }; context.window = context;
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root, 'app/src/main/assets/ui/screens/learning.js'), 'utf8'), context);
const screen = Object.create(context.OmegasUi.LearningScreen.prototype);
screen.cellPane = { innerHTML: '', querySelector: () => null };
const c = payload.comparisons[0];
assert.ok(c);
screen.renderDetail({ learning: payload }, c.cng_cell_row, c.cng_cell_column);
assert.match(screen.cellPane.innerHTML, /Gasolina esperada/);
assert.match(screen.cellPane.innerHTML, /5,00 ms/);
assert.match(screen.cellPane.innerHTML, /5,40 ms/);
assert.match(screen.cellPane.innerHTML, /Diferença/);
assert.match(screen.cellPane.innerHTML, /Confiança/);
assert.match(screen.cellPane.innerHTML, /Novo valor K sugerido/);
assert.match(screen.cellPane.innerHTML, /Abrir o editor não escreve na ECU/);
console.log('JVM_TO_JS_PAYLOAD=PASS');