const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.resolve(__dirname,'../..'),ui=path.join(base,'app/src/main/assets/ui');
function load(){const root={};vm.runInNewContext(fs.readFileSync(path.join(ui,'core/refinement-launch.js'),'utf8'),{window:root});return root.OmegasUi;}
test('notification route survives cold mount then opens Refino once; unknown route does nothing',()=>{const ns=load(),surface={omegasPendingRoute:'refino'},calls=[];assert.equal(ns.consumeLaunchRoute(surface,null),false);assert.equal(surface.omegasPendingRoute,'refino');const router={navigate:r=>{calls.push(r);return true;}};assert.equal(ns.consumeLaunchRoute(surface,router),true);assert.equal(ns.consumeLaunchRoute(surface,router),false);assert.deepEqual(calls,['refino']);surface.omegasPendingRoute='curve';assert.equal(ns.consumeLaunchRoute(surface,router),false);});
test('ready suggestion opens existing review; other phases never create a write',()=>{const ns=load(),s=ns.RefinementLaunch.suggestion({autopilot:{phase:'PROPOSTA_PRONTA'}});assert.equal(s.title,'Curva refinada pronta');assert.equal(s.route,'refino');assert.equal(s.context.review,true);for(const phase of ['SEM_ECU','ECU_TRABALHANDO','COLETANDO_NOSSOS','VERIFICANDO','RESTAURAR_TRECHO','ESTAVEL'])assert.equal(ns.RefinementLaunch.suggestion({autopilot:{phase}}),null);});
test('Android cold/warm intents and UI entrypoints are wired without a timer or auto-write',()=>{const activity=fs.readFileSync(path.join(base,'app/src/main/java/com/omegas/prohub/MainActivity.kt'),'utf8'),notification=fs.readFileSync(path.join(base,'app/src/main/java/com/omegas/prohub/service/NotificationController.kt'),'utf8');assert.match(notification,/putExtra\(NotificationRoute.EXTRA_UI_ROUTE, NotificationRoute.REFINEMENT\)/);assert.match(activity,/receiveUiRoute\(intent\)/);assert.match(activity,/override fun onPageFinished/);assert.match(activity,/omegasPendingRoute/);assert.match(fs.readFileSync(path.join(ui,'app.js'),'utf8'),/ns.consumeLaunchRoute/);assert.match(fs.readFileSync(path.join(ui,'screens/dashboard.js'),'utf8'),/navigate\('refino'\)/);});

test('language never promises physical elimination of a jolt',()=>{const source=fs.readFileSync(path.join(ui,'screens/autocal-evidence.js'),'utf8')+fs.readFileSync(path.join(ui,'screens/autocal-refine.js'),'utf8');assert.match(source,/degrau que tira a linearidade da puxada/i);assert.doesNotMatch(source,/Anti-tranco|ECU oscila|ciclo-limite|tranco (?:some|vai sumir)|Com trancos/);});

test('an open review keeps its chart and context across refresh',()=>{const root={OmegasUi:{},setTimeout(){}};vm.runInNewContext(fs.readFileSync(path.join(ui,'screens/autocal-refine.js'),'utf8'),{window:root});const host={innerHTML:'',addEventListener(){}};let reads=0;const a={available:true,refinementMode:'EQUIVALENCE',points:[{index:0,referenceTimeMs:5,currentRaw:16000,calculatedRaw:17000,currentFactor:1,calculatedFactor:1.04,origin:'MEASURED'}]};const api={refinedAnalysis:()=>{reads++;return a;},equivalence:()=>({samples:reads}),snapshot:()=>({}),createRefinedDraft:()=>({ok:true}),draftReview:()=>({ok:true,points:[{index:0,currentRaw:16000,targetRaw:16500,currentFactor:1,targetFactor:1.01,petrolMs:5}]})};const p=new root.OmegasUi.AutoCalRefinePanel(host,{store:{patch(){}}},api);p.refresh();p.openReview();const before=host.innerHTML;p.refresh();assert.equal(reads,1);assert.equal(host.innerHTML,before);assert.equal(p.reviewPoints[0].calculatedRaw,16500);});
