package com.omegas.prohub.model

data class HubStatus(
    val serviceRunning: Boolean = false,
    val engineRunning: Boolean = false,
    val engineReady: Boolean = false,
    val engineStuck: Boolean = false,
    val engineVersion: String = "--",
    val usbConnected: Boolean = false,
    val usbDevice: String = "Nenhum",
    val usbPermissionPending: Boolean = false,
    val autoReconnectUsb: Boolean = true,
    val baudRate: Int = 9600,
    val serialFormat: String = "8N1",
    val ecuState: String = "OFFLINE",
    val fuelState: String = "--",
    val rpm: Int = 0,
    val petrolMs: Double = 0.0,
    val gasMs: Double = 0.0,
    val mapBar: Double = 0.0,
    val gasPressureBar: Double = 0.0,
    val currentCell: String = "--",
    val kCurrent: Double = 0.0,
    val kSuggested: Double? = null,
    val deltaK: Double? = null,
    val confidence: Double = 0.0,
    val lastError: String = "",
    val wakeLockHeld: Boolean = false,
    val uptimeSeconds: Long = 0L,
    val engineRestarts: Int = 0,
    val healthFailures: Int = 0,
    val storagePath: String = "",
    val workspaceConfigured: Boolean = false,
    val gpsEnabled: Boolean = false,
    val gpsSpeedKmh: Double = 0.0,
    val gpsAccuracyM: Double = 0.0,
    val lanEnabled: Boolean = false,
    val lanAddress: String = "",
    val directTelemetryAgeMs: Long = -1,
)

